# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import mediasiteapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediasiteapp', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyArticles',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mediasiteapp.article',),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to=mediasiteapp.models.generate_filename),
        ),
    ]
